import opensans from "./assets/Fonts/Fonts";
import "./globals.css";

export const metadata = {
  title: "Qexal - Professional Website Builder ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={opensans.className}>{children}</body>
    </html>
  );
}
